# Generated by Django 3.1.2 on 2021-04-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_expense_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='content',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='expense',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
