# Generated by Django 3.1.2 on 2021-04-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20210429_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
