# Generated by Django 3.1.2 on 2021-04-29 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20210429_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': '費用明細'},
        ),
        migrations.AlterModelOptions(
            name='makercard',
            options={'verbose_name': 'メーカー'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': '口コミ'},
        ),
    ]
