# Generated by Django 3.1.2 on 2021-05-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20210429_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='landarea',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
