# Generated by Django 3.1.2 on 2021-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_expense_landarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rate',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
