# Generated by Django 3.1.2 on 2021-05-05 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_reviews_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comment',
            new_name='costcomment',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rate',
        ),
        migrations.AddField(
            model_name='reviews',
            name='attachcomment',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='attachrate',
            field=models.IntegerField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='costrate',
            field=models.IntegerField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='designcomment',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='designrate',
            field=models.IntegerField(default=3.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='guaranteecomment',
            field=models.TextField(default='okok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='guaranteerate',
            field=models.IntegerField(default=4.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='layoutcomment',
            field=models.TextField(default='daijoubu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='layoutrate',
            field=models.IntegerField(default=2.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='salescomment',
            field=models.TextField(default='okokokok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='salesrate',
            field=models.IntegerField(default=5.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='speccomment',
            field=models.TextField(default='warukunai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='specrate',
            field=models.IntegerField(default=1.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='status',
            field=models.CharField(default='見積もり', max_length=100),
            preserve_default=False,
        ),
    ]
