# Generated by Django 3.1.2 on 2021-05-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20210505_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='avgrate',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
