# Generated by Django 3.1.2 on 2021-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_reviews_avgrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='avgrate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
