# Generated by Django 3.1.2 on 2021-05-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0011_auto_20210505_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='comment',
            new_name='costdowncomment',
        ),
        migrations.AddField(
            model_name='expense',
            name='costupcomment',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='gradecomment',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makercard',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='makercard',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='expense'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='review'),
        ),
    ]
