# Generated by Django 3.1.2 on 2021-05-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0012_auto_20210507_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='images',
            new_name='image',
        ),
    ]
