# Generated by Django 3.1.2 on 2021-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0014_auto_20210508_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='makercard',
            name='name_eng',
            field=models.CharField(default='home', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makercard',
            name='name_hira',
            field=models.CharField(default='ホーム', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='makercard',
            name='name_kata',
            field=models.CharField(default='ホーム', max_length=100),
            preserve_default=False,
        ),
    ]
