# Generated by Django 3.1.2 on 2021-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0016_reviews_maker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='maker_name',
            field=models.CharField(default='sekisuiheim', max_length=100),
            preserve_default=False,
        ),
    ]
