# Generated by Django 3.1.2 on 2021-05-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0018_auto_20210520_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(default='見', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='悪くない', max_length=100),
            preserve_default=False,
        ),
    ]
