# Generated by Django 3.1.2 on 2021-05-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0019_auto_20210520_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makercard',
            name='description',
        ),
        migrations.RemoveField(
            model_name='makercard',
            name='images',
        ),
        migrations.RemoveField(
            model_name='makercard',
            name='update_date',
        ),
    ]
