# Generated by Django 3.1.2 on 2021-05-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_auto_20210520_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='makercard',
            name='images',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
