# Generated by Django 3.1.2 on 2021-06-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0021_makercard_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
    ]
