# Generated by Django 3.1.2 on 2021-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0022_remove_expense_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='makercard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
