# Generated by Django 3.1.2 on 2021-06-04 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0023_auto_20210604_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
