# Generated by Django 3.1.2 on 2021-06-22 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0025_auto_20210605_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='makercard',
            name='description',
            field=models.TextField(default='arund'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='makercard',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='create_date',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
