# Generated by Django 3.1.2 on 2021-06-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0026_auto_20210622_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='hidden',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
