# Generated by Django 3.1.2 on 2021-06-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0027_expense_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='hidden',
            new_name='hid',
        ),
    ]
