# Generated by Django 3.1.2 on 2021-06-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0028_auto_20210624_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='attachcomment',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='attachrate',
        ),
        migrations.AddField(
            model_name='expense',
            name='layoutimage',
            field=models.ImageField(blank=True, null=True, upload_to='expense/'),
        ),
    ]
