# Generated by Django 3.1.2 on 2021-06-24 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0029_auto_20210624_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='image',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='expense/')),
                ('name', models.CharField(default='example.png', max_length=250, verbose_name='ファイル名')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='house.expense')),
            ],
        ),
    ]
