# Generated by Django 3.1.2 on 2021-06-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0030_auto_20210625_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='layoutimage',
        ),
    ]
