# Generated by Django 3.1.2 on 2021-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0031_remove_expense_layoutimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expimage',
            field=models.ImageField(blank=True, null=True, upload_to='expense/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='layoutimage',
            field=models.ImageField(blank=True, null=True, upload_to='expense/'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
